/* SPDX-License-Identifier: GPL-3.0-or-later */
#pragma once
#include "waveshare_p4_xz_map.h"
#define N_AXIS 3 // XYZ indexing is retained; the example has only X/Z outputs.
#define DEFAULT_LATHE_MODE 1
#define LATHE_UVW_OPTION 1
#define NGC_EXPRESSIONS_ENABLE 1
#define COMPATIBILITY_LEVEL 0
#define DEFAULT_X_STEPS_PER_MM 1200.0f
#define DEFAULT_Z_STEPS_PER_MM 200.0f
#define DEFAULT_X_MAX_RATE 60.0f
#define DEFAULT_Z_MAX_RATE 960.0f
#define DEFAULT_X_ACCELERATION 25.0f
#define DEFAULT_Z_ACCELERATION 50.0f
#define DEFAULT_STEP_PULSE_MICROSECONDS 10.0f
#define DEFAULT_STEP_PULSE_DELAY 5.0f
#define DEFAULT_STEPPER_IDLE_LOCK_TIME 255
#define DEFAULT_HOMING_ENABLE 0
#define DEFAULT_ENABLE_SIGNALS_INVERT_MASK 1
#define DEFAULT_DIR_SIGNALS_INVERT_MASK 4
#define DEFAULT_STEP_SIGNALS_INVERT_MASK 0
#define P4_STEP_HZ 10000000UL
#define SPINDLE_SYNC_ENABLE 1
#define DEFAULT_SPINDLE_PPR P4_ENCODER_CPR
#if P4_BENCH_ONLY
#define BUILD_INFO "P4_EXPERIMENTAL_ENABLES_LOCKED"
#else
#define BUILD_INFO "P4_EXPERIMENTAL_AXIS_CONTROL"
#endif
